// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqykgdpyfryweqtbqrdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxeWtnZHB5ZnJ5d2VxdGJxcmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2ODkyNTksImV4cCI6MjA1NjI2NTI1OX0.cEyOgqv7wV2o32buA46qSZXL0vZu1GBiYGLacnlfHK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);